---
- name: Configure  LDAP server for login using cli
  hosts: ldap
  remote_user: ansible
  become: yes

  # Getting Admin credential
  vars_prompt:
    - name: adm_passwd
      prompt: "Enter LDAP Admin password"

  tasks:
  - name: Disable SELinux
    shell: setenforce 0
    ignore_errors: yes

  - name: Disable SELinux permanently
    lineinfile: dest=/etc/sysconfig/selinux regexp="SELINUX=" line="SELINUX=disabled"

  - name: turn off firewall for install
    service:
      name: firewalld
      state: stopped
      enabled: false

  - name: Installing packages
    yum:
      name: ['openldap', 'openldap-clients', 'openldap-servers', 'openssl']
      state: latest

  - name: start slapd
    service:
      name: slapd
      state: started
      enabled: true

  - name: import domain structure
    copy: src=./tmplates/hdb.ldif dest=./hdb.ldif

  - name: Generate the root password for ldap
    shell: "(echo 'olcRootPW: ' | tr -d '\n'  &&  slappasswd -s {{adm_passwd}}) >> ./hdb.ldif"

  - name: Copy sample db config
    copy:
      src: "/usr/share/openldap-servers/DB_CONFIG.example"
      dest: "/var/lib/ldap/DB_CONFIG"
      directory_mode: yes
      remote_src: yes
      directory_mode: yes
      owner: ldap
      group: ldap

  - name: modifying olcDatabase
    shell: ldapmodify -Y EXTERNAL -H ldapi:/// -f hdb.ldif

  - name: import monitoring structure
    copy: src=./tmplates/monitor.ldif dest=./monitor.ldif

  - name: setting up monitoring privileges
    shell: ldapmodify -Y EXTERNAL -H ldapi:/// -f monitor.ldif

  - name: start the slapd service
    service: name=slapd state=started enabled=yes

  - name: Import base structure
    copy: src=./tmplates/base.ldif dest=./base.ldif

  - name: Authenticating cosine
    shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif

  - name: Authenticating nis
    shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/nis.ldif

  - name: Authenticating inetorgperson
    shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif

  - name: Importing user creation sample
    copy: src=./tmplates/user.ldif dest=./user.ldif

  - name: Importing group creation sample
    copy: src=./tmplates/group.ldif dest=./group.ldif

  - name: Importing user modification sample
    copy: src=./tmplates/modify_user.ldif dest=./modify_user.ldif

  - name: Installing Apache
    yum:
      name: httpd
      state: latest

  - name: start httpd service
    service:
      name: httpd
      state: started
      enabled: yes

  handlers:
    - name: restart slapd
      service:
        name: slapd
        state: restarted

