---
- name: mount nfs share on allclient boxes
  hosts: all, !ldap, !nfs
  remote_user: ansible
  become: yes

  tasks:
  - name: Change auto master configuration file
    blockinfile:
      path: /etc/auto.master
      insertafter: EOF
      block: |
        #The following entry is for indirect automounting for ldap user
        # Shares indicated in mapping file will be automounted on top of /indirect folder
        #mountpoint mapping file timeout
        /prdx-ldap13/home  auto.home --timeout 60

  - name: copy mapping file
    template:
      src: ./tmplates/ldapmnt.conf.j2
      dest: /etc/auto.home

  - name : restart autofs
    service: name=autofs
             state=restarted
             enabled=yes
