
---
- hosts: prometheus
  remote_user: ansible
  become: yes
  tasks:
  - name: add user prometheus
    shell: useradd -m -s /bin/bash -p `openssl passwd password` prometheus
  - name: switch to prometheus
    shell: su - prometheus
  - name: install required packages
    shell: wget https://github.com/prometheus/prometheus/releases/download/v2.2.1/prometheus-2.2.1.linux-amd64.tar.gz
- name: extract file
  shell: tar xvfz prometheus-2.2.1.linux-amd64.tar.gz
  - name: install docker
    yum:
      name: docker-ce, bridge-utils
      state: latest
    notify: restart docker
  - name: ensure docker is running
    service:
      name: docker
      state: started
  - name: enable service docker
    systemd:
      name: docker
      enabled: yes
  handlers:
      - name: restart docker
        service:
          name: docker
          state: restarted
