---
# tasks file for myfirewall
- name: Install firewalld
  yum:
    name: firewalld
    state: latest

- name: start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: true

- name: firewall services config
  firewalld:
    state: enabled
    immediate: true
    permanent: true
    service: "{{ firewall_service }}"
     
