---
# tasks file for myfirewall
- name: Install firewalld
  yum:
    name: firewalld
    state: latest

- name: start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: true

-
