---
# tasks file for samba
  vars_prompt:
    - name: smb_usrname
      prompt: "Enter samba share username"

    - name: smb_passwd
      prompt: "Enter samba share password"
      private: yes

- name: install samba
  yum:
    name: [ samba samba-common samba-client ]
    state: latest
